blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/dwenzel/t3extension-tools/blob/master/README.md
    about: Check the documentation for usage examples and guides
  - name: Discussions
    url: https://github.com/dwenzel/t3extension-tools/discussions
    about: Ask questions and discuss ideas with the community