name: Static Analysis

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  phpstan:
    name: "PHPStan"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_sqlite
          coverage: none

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: dependencies-php-8.2-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-php-8.2-composer-

      - name: Install dependencies
        run: |
          composer require phpstan/phpstan:^1.10 --no-progress --dev
          # Create a skeleton TYPO3 project structure for PHPStan
          mkdir -p .Build/Web/typo3conf/ext/
          ln -s ../../../../. .Build/Web/typo3conf/ext/t3extension_tools

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon